In [158]:
# 79-character line limit
######### ######### ######### ######### ######### ######### ######### #########
%reset -f

import numpy as np # The NumPy library
#import math # The math module, np includes it
from scipy.integrate import quad # Method for integration in scipy.integrate sub-package
from scipy.optimize import linprog


cells_num = 8

# The sizes are for UQs for number of cells: 4, 8, 16, 32, 64, 128, 256.

# The opitimized spaces for the Guassian distribution in a uniform quantizer(UQ).
all_size_gaus = np.array([0.9957, 0.5860, 0.3352, 0.1881, 0.1041, 0.0569, 0.0308])

# The opitimized spaces for the Laplacian distribution in a uniform quantizer(UQ).
all_size_laplacian = np.array(
                   [1.414, 1.0873, 0.8707, 0.7309, 0.6334, 0.5613, 0.5055])

'''To change the symmetric pdf, two parts of code must be changed include the 
cell_size and pdf'''

cell_size = all_size_gaus[int(np.log2(cells_num))-2]
# cell_size = all_size_laplacian[int(np.log2(cells_num))-2]

# np.arange has rounding error issue.
# boundaries_symm = np.arange(-(cells_num/2-1) * cell_size, # For symmetric distributions
#                              (cells_num/2) * cell_size,
#                             cell_size) 

boundaries_symm = np.linspace(-(cells_num/2-1) * cell_size, # For symmetric distributions
                               (cells_num/2-1) * cell_size,
                              cells_num-1)
n_inf = float("-inf")
p_inf = float("inf")

boundaries_symm = np.insert(boundaries_symm, 0, n_inf)
boundaries_symm = np.append(boundaries_symm, p_inf)

def pdf(x): # Defining the distribution
    gaus_std = 1
    gaus_mean = 0
    pdf = 1/(gaus_std*np.sqrt(2*np.pi)) * \
                  np.exp(-0.5*((x-gaus_mean)/gaus_std)**2) # Gaussian pdf
    
#     div = 1
#     pdf = 1/(2*div)*np.exp(-abs(x)/div)
    
    return pdf

def xpdf(x):
    xpdf = x * pdf(x)
    return xpdf

def x2pdf (x):
    x2pdf = x * xpdf(x)
    return x2pdf


prbs = []
xprbs = []
x2prbs = []
cell_reps = []
for i in range (0, cells_num):
    cell_prb, integ_err = quad(pdf, boundaries_symm[i], boundaries_symm[i+1])
    prbs = np.append(prbs, cell_prb)
    
    cell_xprb, integ_err = quad(xpdf, boundaries_symm[i], boundaries_symm[i+1])
    xprbs = np.append(xprbs, cell_xprb)
    
    cell_x2prb, integ_err = quad(x2pdf, boundaries_symm[i], boundaries_symm[i+1])
    x2prbs = np.append(x2prbs, cell_x2prb)
    
    cell_rep = cell_xprb / cell_prb
    cell_reps = np.append(cell_reps, cell_rep)
    
    
'''The centroids and distortions of all possible pairs are calculated 
based on the strategy 1.'''

all_yijs = []
all_dijs = []
for i in range(0,cells_num-1):
    for j in range(i+1,cells_num):
        possible_yij = (xprbs[i] + xprbs[j])/(prbs[i] + prbs[j])
        all_yijs = np.append(all_yijs, possible_yij)
    
        possible_dij\
        = x2prbs[i] + possible_yij**2 * prbs[i] - possible_yij *2 * xprbs[i]\
        + x2prbs[j] + possible_yij**2 * prbs[j] - possible_yij *2 * xprbs[j]
        all_dijs = np.append(all_dijs, possible_dij)
        

# We implement the linear programming.
obj_coef = -all_dijs
all_length = int(cells_num * (cells_num-1) / 2)

A_eq = np.zeros([cells_num, all_length])
k = 0
for i in range(0, cells_num-1):
    for j in range(i+1,cells_num):
        A_eq[i,k]=1
        k+=1
k = 0
for j in range(1, cells_num):
    for i in range (j,cells_num):
        A_eq[i,k]=1
        k+=1

b_eq = np.ones([cells_num,])

result = linprog(obj_coef, A_eq=A_eq, b_eq=b_eq)
opt_xs = result.x
opt_pairs = np.round(result.x) # Pairs
opt_distortion = -result.fun # Value of the distortion

k = 0
xx = np.zeros([cells_num, cells_num])
for i in range(0,cells_num):
    for j in range(i+1,cells_num):
        xx[i,j] = opt_pairs[k]
        k +=1
xx = xx + np.transpose(xx)
yy = np.where(xx)
zz = np.append(yy[0],yy[1])
pairs = np.reshape(zz,[2,cells_num])
pairs = pairs[:,0:int(cells_num/2)]

print(opt_distortion)
# print(opt_xs)
# print(opt_pairs)
print(pairs)

0.9999999999988477
[[0 1 2 3]
 [7 6 5 4]]


In [159]:
all_yijkls = []
all_dijkls = []
for i in range (0, int(cells_num/2)-1):
    for j in range(i+1,int(cells_num/2)):
        possible_yijkl\
        = ((xprbs[pairs[0,i]] + xprbs[pairs[1,i]])
        + (xprbs[pairs[0,j]] + xprbs[pairs[1,j]]))\
        /((prbs[pairs[0,i]] + prbs[pairs[1,i]])
        +(prbs[pairs[0,j]] + prbs[pairs[1,j]])) 
        
        all_yijkls = np.append(all_yijkls, possible_yijkl)
        
        possible_dijkl\
        = x2prbs[pairs[0,i]] + possible_yijkl**2 * prbs[pairs[0,i]]\
        - possible_yijkl *2 * xprbs[pairs[0,i]]\
        + x2prbs[pairs[1,i]] + possible_yijkl**2 * prbs[pairs[1,i]]\
        - possible_yijkl *2 * xprbs[pairs[1,i]]\
        + x2prbs[pairs[0,j]] + possible_yijkl**2 * prbs[pairs[0,j]]\
        - possible_yijkl *2 * xprbs[pairs[0,j]]\
        + x2prbs[pairs[1,j]] + possible_yijkl**2 * prbs[pairs[1,j]]\
        - possible_yijkl *2 * xprbs[pairs[1,j]]
        
        all_dijkls = np.append(all_dijkls, possible_dijkl)
        
# We implement the linear programming.
quad_obj_coef = -all_dijkls
all_length_half = int(cells_num/2 * (cells_num/2-1) / 2)

A_eq_half = np.zeros([int(cells_num/2), all_length_half])
k = 0
for i in range(0, int(cells_num/2-1)):
    for j in range(i+1,int(cells_num/2)):
        A_eq_half[i,k]=1
        k+=1
k = 0
for j in range(1, int(cells_num/2)):
    for i in range (j,int(cells_num/2)):
        A_eq_half[i,k]=1
        k+=1

b_eq_half = np.ones([int(cells_num/2),])

quad_result = linprog(quad_obj_coef, A_eq=A_eq_half, b_eq=b_eq_half)
opt_xs_quad = quad_result.x
opt_quad = quad_result.x # Pairs
opt_distortion_quad = -quad_result.fun # Value of the distortion

print(opt_distortion_quad)
print(opt_xs_quad)

1.000000000085425
[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]


In [160]:
# print(all_dijkls[0]+all_dijkls[5])
# print(all_dijkls[1]+all_dijkls[4])
# print(all_dijkls[2]+all_dijkls[3])

In [161]:
# We calculate the distortion of 2MSBs encryption for NBIA.

nb_all_yijkls = []
nb_all_dijkls = []
power = np.log2(cells_num)
for i in range(0,int(cells_num/4)):
    j = int(i + 2**(power-2))
    k = int(i + 2**(power-2)*2)
    l = int(i + 2**(power-2)*3)
    print(i,j,k,l)
    
    nb_yijkl = (xprbs[i]+xprbs[j]+xprbs[k]+xprbs[l])\
             / (prbs[i]+prbs[j]+prbs[k]+prbs[l]) 
        
    nb_all_yijkls = np.append(nb_all_yijkls, nb_yijkl)
        
    nb_dijkl = x2prbs[i] + nb_yijkl**2 * prbs[i] - nb_yijkl *2 * xprbs[i]\
             + x2prbs[j] + nb_yijkl**2 * prbs[j] - nb_yijkl *2 * xprbs[j]\
             + x2prbs[k] + nb_yijkl**2 * prbs[k] - nb_yijkl *2 * xprbs[k]\
             + x2prbs[l] + nb_yijkl**2 * prbs[l] - nb_yijkl *2 * xprbs[l]
    
    nb_all_dijkls = np.append(nb_all_dijkls, nb_dijkl)
    
nb_distortion = np.sum(nb_all_dijkls)
print(nb_distortion)

0 2 4 6
1 3 5 7
0.9930353054347388


0.050129421861401874